project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Jiawei Chen"
  site-url: https://jiaweichen.github.io
  favicon: images/site-logo-C.jpg
  repo-url: https://jiawei-chen1205.github.io/jiaweichen.github.io/
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
      [\@ 2025 Jiawei Chen](https://jiawei-chen1205.github.io/jiaweichen.github.io/)<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      # - text: "Books"
      #   href: books.qmd
      # - text: "Blogs"
      #   href: blog.qmd
      # - text: "Codes"
      #   href: codes.qmd
      - text: "Others"
        href: others.qmd
      - text: "Chinese"
        href: Chinese.qmd
      # - text: "CV"
      #   href: CV.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细